make sample tool sources .cpp to get proper linking; makefile updates
git-svn-id: https://scripts.sil.org/svn/teckit/TRUNK@58 46987711-6ee3-0310-9c75-c0fe504237a4

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -465,7 +465,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CC CFLAGS ac_ct_CC CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE build build_cpu build_vendor build_os host host_cpu host_vendor host_os EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL SYSTEM_EXPAT_TRUE SYSTEM_EXPAT_FALSE LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CC CFLAGS ac_ct_CC CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE build build_cpu build_vendor build_os host host_cpu host_vendor host_os EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL SYSTEM_ZLIB_TRUE SYSTEM_ZLIB_FALSE SYSTEM_EXPAT_TRUE SYSTEM_EXPAT_FALSE LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -18703,6 +18703,18 @@ _ACEOF
 fi
 
 
+
+if test x$ac_cv_lib_z_compress = xyes; then
+  SYSTEM_ZLIB_TRUE=
+  SYSTEM_ZLIB_FALSE='#'
+else
+  SYSTEM_ZLIB_TRUE='#'
+  SYSTEM_ZLIB_FALSE=
+fi
+
+SYSTEM_ZLIB=no
+
+
 echo "$as_me:$LINENO: checking for XML_ExpatVersion in -lexpat" >&5
 echo $ECHO_N "checking for XML_ExpatVersion in -lexpat... $ECHO_C" >&6
 if test "${ac_cv_lib_expat_XML_ExpatVersion+set}" = set; then
@@ -18775,7 +18787,6 @@ _ACEOF
   LIBS="-lexpat $LIBS"
 
 fi
-
 
 
 
@@ -19191,6 +19202,13 @@ if test -z "${am__fastdepCC_TRUE}" && test -z "${am__fastdepCC_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"am__fastdepCC\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"am__fastdepCC\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${SYSTEM_ZLIB_TRUE}" && test -z "${SYSTEM_ZLIB_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"SYSTEM_ZLIB\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"SYSTEM_ZLIB\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -19805,6 +19823,8 @@ s,@F77@,$F77,;t t
 s,@FFLAGS@,$FFLAGS,;t t
 s,@ac_ct_F77@,$ac_ct_F77,;t t
 s,@LIBTOOL@,$LIBTOOL,;t t
+s,@SYSTEM_ZLIB_TRUE@,$SYSTEM_ZLIB_TRUE,;t t
+s,@SYSTEM_ZLIB_FALSE@,$SYSTEM_ZLIB_FALSE,;t t
 s,@SYSTEM_EXPAT_TRUE@,$SYSTEM_EXPAT_TRUE,;t t
 s,@SYSTEM_EXPAT_FALSE@,$SYSTEM_EXPAT_FALSE,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
